# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
fullname: "Jack Cooc"
title: Jack Cooc – Toronto based Front-end Web Developer and UX Designer
email: jack.cooc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Did you just use Google to look for a front-end web devloper in the Toronto area? 
  Click on the link above to check out my portfolio and see what I'm about!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jackcooc.com/" # the base hostname & protocol for your site, e.g. http://example.com
twitter: jackcooc

# Website Text
#About me section
about: I am a Toronto based web developer with experience in creating web solutions, most recently focusing on user experience design. I am passionate about building web experiences using robust, extensible frameworks and tools, always striving to continuously learn new skills and the latest technologies in each of my projects.
# What do I know?
iknow: I have done everything from front-end development, to back-end development to systems deployment on Amazon AWS EC2 instances. I have a wide variety of experience

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
permalink: /work/:title
